### ISSUE TITLE
Yola.change_site_domain 404s

### ISSUE THREAD

**Issue by blaix** [yola/yolapy#19]
`Yola.change_site_domain` errors with a 404. I haven't figured out why, or if the fault is in yolapy, wl-proxy, or sbbe.  (partially blocking #3)

**Comment by snitch** [comment]
@blaix: This issue is now a priority.

**Comment by ekoval** [comment]
I've verified this and it works for me without YolaPy:

```
curl -H "Content-Type:application/json" -u WL_TOPLINE:...8c4 -X PUT -d '{"partner_domain":"www.ddd"}' https://wl.qa.yola.net/sites/ff8081813eefb1ea013f132438e803d1/partner_domain/ 
```

Response:

```
{"id":"ff8081813eefb1ea013f132438e803d1","name":"Stalkers Inc","screenshot_url":null,"preview_url":"/template_resources/0/Suarez/thumbnails/192x192.gif","created_at":"2013-06-05T07:01:48","last_edited_at":"2015-11-06T16:48:10","last_opened_at":"2015-11-06T16:48:10","deleted_at":null,"storage_used":0,"is_archived":false,"is_defunct":false,"user_id":"38e2afc86615457d83ca6532b6ab0a41"}
```

I had 404 ("Partner Domain not found") there until I've added partner domain for this site manually using Django ORM. 
Is it possible that you're trying to specify partner domain name, which just doesn't exist?

I've also reviewed code in YolaPy and it seems so straightforward that I can't believe it is it's issue.

**Comment by blaix** [comment]
It sounds like the problem is that we 404 when trying to PUT a domain on a site that doesn't have one yet. Please consider that the fix you need to make here.

**Comment by snitch** [comment]
@ekoval: This issue is now a priority.

**Comment by blaix** [comment]
Also, please restore this test once the issue is resolved: https://github.com/yola/yolapy/commit/36229bab9d72fe4f3e6c48f52e0ec65985a3099a

**Comment by RayeN** [comment]
@blaix Do we have a real use case for it?  I mean AFAIK right now partners cannot create site without `partner_domain`.  And we have a complete mess with creation vs update right now.  Side effects for creation are done in JSBBE, but for update - in SBBE.  I think `creation on update` flow will probably be used only in tests (but might be wrong) atm.   

So, what I'm trying to say here - I'm not sure if we should just fix it in that method, without considering how should our flow look like in general.

**Comment by blaix** [comment]
are you saying if a site is created without a partner domain, it can never have one?

**Comment by RayeN** [comment]
I mean that the current flow won't allow you to create one, I think.

**Comment by RayeN** [comment]
SSO URL contains partner_domain name AFAIK

**Comment by ekoval** [comment]
So current behavior seems correct?

**Comment by RayeN** [comment]
I'm not sure about correctness. Just want to say that the scenario we are about to handle here won't be used in real flow.   And also it might not have much sense - for real flow.  Let me try to explain: 
- We create site without partner domain - means site isn't published.
- We set partner_domain via the `change_site_domain` endpoint - site is still unpublished
- When we publish site - it will do all the things we already did in `change_site_domain` once again.

**Comment by ekoval** [comment]
So maybe I'll just reMOVE a failing test? :)

**Comment by blaix** [comment]
@RayeN can you explain to me what the relationship is with publishing a site and setting a partner domain? I didn't realize publishing was involved in _setting_ it.

**Comment by RayeN** [comment]
Sorry, looks like I confused myself and everyone else :(  Just ignore all my comments.  Setting partner domain shouldn't be related to publishing (and it isn't).  So, we should allow to create partner domain on update. Sorry again for confusing.

**Comment by blaix** [comment]
> It sounds like the problem is that we 404 when trying to PUT a domain on a site that doesn't have one yet. Please consider that the fix you need to make here.

So do we all agree that this is the fix we need? If so, we should create the issue on sbbe.

**Comment by RayeN** [comment]
Yeah, I think we're on the same page now.  Please create a proper ticket.

**Comment by ekoval** [comment]
##### Status

Solution is known, estimate - 4 hours.
