### ISSUE TITLE
Yola.list_campaigns 500s

### ISSUE THREAD

**Issue by blaix** [yola/yolapy#20]
`Yola.list_campaign` is responding with a 500. This is preventing me from testing any of the other campaign methods (partially blocking #3).

**Comment by blaix** [comment]
I didn't think the error was being logged, but I was looking in the wrong place. From @RayeN:

> If it's in async task handler - you should take a look at celery log
> `/var/log/yola/sitewitservice-celery.log`
> 
> both log for sitewitservice and its celery worker reside in `/var/log/yola/` btw

**Comment by snitch** [comment]
@blaix: This issue is now a priority.

**Comment by blaix** [comment]
Make sure this test case get's restored and fleshed out after the issue is resolved: be4db8d

**Comment by snitch** [comment]
@ekoval: This issue is now a priority.

**Comment by ekoval** [comment]
Error: https://app.getsentry.com/yola/sitewitservice-2/group/97576806/

**Comment by ekoval** [comment]
@RayeN this seems to be the same problem as you recently has with `hasattr` applied to `@property`-decorated method. Permission checker tries (https://github.com/yola/yopartners/blob/master/yopartners/contrib/drf/permissions.py#L47) to find site, fails with 404 exception, and hasattr returns `False`.
