### ISSUE TITLE
Yola.change_subscription_type does not change subscription type

### ISSUE THREAD

**Issue by blaix** [yola/yolapy#21]
``` python
yola = Yola(
  url='https://wl.yolapy-tests.env.yola.net/',
  auth=('WL_TOPLINE', '[REDACTED]'))
user = yola.create_user(
  email='test+%s@yola.com' % uuid4().hex,
  name='John',
  surname='Smith',
  partner_id='WL_YOLA',
  preferences={})
sub = yola.create_subscription('wl_basic', user['id'], {'foo': 'bar'})
sub['type'] # => u'wl_basic'
yola.change_subscription_type(sub['id'], 'wl_lite')
sub = yola.get_subscription(sub['id'])
sub['type'] # => u'wl_basic'
```

Partially blocking #3

**Comment by RayeN** [comment]
Is `wl_lite` allowed for `WL_YOLA`?

**Comment by blaix** [comment]
I didn't realize there were permissions involved. Can you point me in the right direction to find out?

If it's not allowed, should something other than a 2xx be returned from the POST?

**Comment by RayeN** [comment]
Yeah, it shouldn't return 2xx because it's exposed to partners.

**Comment by RayeN** [comment]
so, there are 2 issues here:
1. Michango doesn't check for `available_subscription_types` in case of subscription creation.
2. Michango returns 200 when provided type isn't allowed for certain partner (but it should return 403 I suppose)

and your partner `WL_YOLA` on your env doesn't have any properties - so available subscription types are []

**Comment by blaix** [comment]
Still getting the same failure when I use a partner that I created with `properties={'available_subscription_types': ['wl_basic', 'wl_lite']}`. I need to step away, but when I come back I'll try again and paste the example code.

**Comment by stefanor** [comment]
> Michango returns 200 when provided type isn't allowed for certain partner (but it should return 403 I suppose)

or 400. 403 means this is possible, but _you_ don't have permission. However, no matter who you are, this won't be possible, unless the partner is modified.

**Comment by blaix** [comment]
New example, this time with `available_subscription_types`:

```
>>> partner = yola.create_partner(
...   id='WL_TEST-abc123', name='TEST', parent_partner_id='WL_TOPLINE',
...   properties={'website': 'example.com', 'available_subscription_types': ['wl_basic', 'wl_lite']})
>>> partner['properties']['available_subscription_types']
[u'wl_basic', u'wl_lite']
>>> user = yola.create_user(
...   email='justin+testabc123@yola.com', name='Justin', surname='Danger',
...   partner_id='WL_TEST-abc123', preferences={})
>>> sub = yola.create_subscription('wl_basic', user['id'], {})
>>> sub['type']
u'wl_basic'
>>> yola.change_subscription_type(sub['id'], 'wl_lite')
>>> updated_sub = yola.get_subscription(sub['id'])
>>> updated_sub['type']
u'wl_basic'
```

Part of this issue will be determining if the problem is in yolapy, wl-proxy, or michango. If it's not in yolapy, issues should be created in the proper project.

@RayeN when you get a chance, please create michango issues for the `available_subscription_types` check and status code issues you described.

**Comment by RayeN** [comment]
@blaix, done:   they are https://github.com/yola/michango/issues/586 and https://github.com/yola/michango/issues/587

@stefanor yeah, agree.  We should probably respond with 400 in such cases.

**Comment by snitch** [comment]
@blaix: This issue is now a priority.

**Comment by RayeN** [comment]
Already closed related Michango's tickets (from the code - it works as expected).  I'll try to repro your steps.

**Comment by blaix** [comment]
Reminder to myself to restore this test once the issue is resolved: https://github.com/yola/yolapy/commit/508c3682ebf506422eeacb32dcaf42d1a779afe6

**Comment by snitch** [comment]
@ekoval: This issue is now a priority.

**Comment by ekoval** [comment]
Started
