### ISSUE TITLE
Yola.activate_trial_subscription should return the newly activated subscription

### ISSUE THREAD

**Issue by blaix** [yola/yolapy#25]
See https://github.com/yola/yolapy/issues/24#issuecomment-153669163

**Comment by snitch** [comment]
@beck: This issue is now a priority.

**Comment by blaix** [comment]
Make sure this test gets restored after the issue is resolved: https://github.com/yola/yolapy/commit/a95a49086bb3cbd78e11c8c4d848363e9432c182

**Comment by blaix** [comment]
@ekoval did this in #34
