### ISSUE TITLE
Provide package properties

### ISSUE THREAD

**Issue by beck** [yola/yolapy#31]
When adding any advertising sub, I get an error saying `currency` is a required preference.

When trying to build a package selector, what's needed:
- what are the available properties for a each subscription type
- which props are required
- what are the acceptable values

This could be just documentation (then all will be hard coded in the app as individual forms for each and every subscription type) but if we can design a programmatic solution, that would be nice.

**Comment by beck** [comment]
ping @RayeN

**Comment by stefanor** [comment]
Looks documented in the browseable API, to me: 

```
    Properties are defined using "properties" key.

    Optional properties:

        "trial" (boolean): should be passed only when subscription is Trial.

    Required properties (only in case of Advertising products):

        "campaign_id" (str) SiteWit campaign ID.
        "site_id" (str) Yola Site ID.
        "currency" (str) campaign's currency.
```

**Comment by beck** [comment]
Thanks @stefanor, I missed that.

Last question: how do we define "trial"?

**Comment by stefanor** [comment]
@brentv?

**Comment by RayeN** [comment]
So, for now for all subscription types (except for ecommerce types) it's just a flag in properties.  For ecommerce we use separate trial plan.  And you shouldn't be able to create Advertising sub in trial mode - if you are - it's a bug.

But we've decided to enforce trial policy on our side as well:  https://github.com/yola/production/issues/2880

**Comment by beck** [comment]
cool cool cool
