### ISSUE TITLE
add **kwargs param to User.__init__ or replace explicit params with double splat?

### ISSUE THREAD

**Issue by highflyingaction** [yola/yolapy#73]
yolapy's [`User.__init__`](https://github.com/yola/yolapy/blob/1be7388d72d12fc0cef5769b0dd72acb3b6a9698/yolapy/models/user.py#L23-L25) expects lots of parameters but doesn't accept `**kwargs`.

This makes it very fragile if the userservice endpoints ever change what they return.
For example, `resetKey` was [recently removed from the `UserPrivateSerializer.exclude` list](https://github.com/yola/userservice/commit/cc60ed11ca653899f3cf0ae550f0eeaf1f2bea79#diff-2307e00f916a8e601ffe2cb7addbc759) and that broke bottomline integration tests because yolapy just [passes whatever the service returns to init](https://github.com/yola/yolapy/blob/1be7388d72d12fc0cef5769b0dd72acb3b6a9698/yolapy/models/user.py#L60-L62)

yolapy's `Site`, `SiteImport`, and `Subscription` models all only have a single `**attrs` style param for their `__init__`s so maybe there is some reason that `User` has explicit params that I'm just not thinking of.

What do we all think about adding `**kwargs` to yolapy's `User.__init__` or just replacing all the named params with `**kwargs`?
@yola/service-engineering

**Comment by jslang** [comment]
Apparently we accept the generalized kwargs for [update operations](https://github.com/yola/yolapy/blob/1be7388d72d12fc0cef5769b0dd72acb3b6a9698/yolapy/models/user.py#L83). No reason we couldn't do that for init too, as far as I can tell. I definitely vote for us doing what we do with the other models.

**Comment by blaix** [comment]
I'm guessing it was a sentiment along the lines of explicit is better than implicit, but  `**kwargs` has been working well in our other client models so I'm all for doing it here too.
