### ISSUE TITLE
Question about `partner_id` and user creation

### ISSUE THREAD

**Issue by beck** [yola/yolapy#9]
Can `partner_id` not be required?

After implementing `create_user` passing `partner_id` seemed unneeded, it should default to the username of the configured client.

Being able to set the `partner_id` to anything BUT my client username seems like an action that should not happen, unless I am creating users for a sub partner, in which case I'd expect the kwarg to be `sub_partner_id` and there be some perm checks to ensure I can indeed create a user with such a partner id.

ping @blaix

**Comment by blaix** [comment]
I don't think allowing resource creation with partner ids that aren't you or your children is enough of a security risk to complicate things by introduce a `sub_partner_id` psuedo-attribute to the API and/or client. @RayeN what do you think?

**Comment by blaix** [comment]
If we do care, we should validate it server-side.

And then default partner_id to the username in the client.

**Comment by RayeN** [comment]
I think we do validate that on service side - at least for user creation.  And I agree with @blaix we should accept partner_id (to allow user creation for sub partners) and default it to the one in client (didn't check the code, but I believe it's the partner_id client is initialized with?).

**Comment by blaix** [comment]
@beck How do you feel about keeping `partner_id`, but defaulting it to the initialized partner id, and letting it be validated server-side?

**Comment by beck** [comment]
I feel good about it
